### ISSUE TITLE
Export to new device

### ISSUE THREAD

**Issue by strdr4605** [cofeed-19/cofeed-19.github.io#1]
Users should be able to export the state of feeds and import on a new browser/laptop/device.

The "Copy feed urls" button should be replaced with the "Export feed" button.
The user will paste the data on a new device in the input and localStorage should be set to the state as on the previous device.

**Comment by strdr4605** [comment]
I think the best UX is to give users an URL with an encrypted state as a query param.
For this use case most probably need a compressed version of the visited URLs.

These libraries may help:
https://www.npmjs.com/package/brotli
https://github.com/Brooooooklyn/snappy
https://github.com/beatgammit/gzip-js

**Comment by maximvolosenco** [comment]
Tested gzip-js, the library archives the data quite well, but I didn't find a way to unzip it, the "unzip(data)" function doesn't work properly.

**Comment by maximvolosenco** [comment]
Found compression/decompression algorithm with good conversion size, it converts 8510 characters (about 230 links) in 2020 characters (maximum allows length for Chrome and internet explorer is 2048 character - 2 mb): 
https://stackoverflow.com/questions/3640357/how-to-compress-a-string
I'm still investigating.
