### ISSUE TITLE
Migrate to IndexedDB

### ISSUE THREAD

**Issue by strdr4605** [cofeed-19/cofeed-19.github.io#17]
Probably IndexedDB is a better choice for the app. Further investigation is needed

**Comment by maximvolosenco** [comment]
I'll take this issue.

**Comment by strdr4605** [comment]
Probably we should read this and decide what works for us:
https://paultman.com/from-localstorage-to-indexeddb/
https://paultman.com/best-library-for-indexeddb-localforage-idb-keyval-or-idb/

**Comment by strdr4605** [comment]
Any progress here?

**Comment by maximvolosenco** [comment]
Good example of CRUD operations for indexeddb: 
https://javascript.plainenglish.io/working-with-indexeddb-in-typescript-react-ad504a1bdae3

**Comment by maximvolosenco** [comment]
Done with implementing CRUD and created functions for inserting and fetching data to/from database.

**Comment by strdr4605** [comment]
Please open a PR or Draft PR?

**Comment by maximvolosenco** [comment]
Done with PR changes, please check.

**Comment by strdr4605** [comment]
Closed by https://github.com/cofeed-19/cofeed-19.github.io/pull/25
