### ISSUE TITLE
RFC: Use SCSS modules

### ISSUE THREAD

**Issue by zvonimirr** [cofeed-19/cofeed-19.github.io#45]
I would like to hear opinions about switching to SCSS modules.
They're exactly like CSS ones just written in SCSS.
I personally think they would allow for much cleaner styling.

Let me know what you think!

CC: @strdr4605

**Comment by strdr4605** [comment]
I understand the benefit of SCSS with nesting and `&`, so I probably am for it. 
But I don't have much experience with it and would not use many features. 
Example: I would stick to CSS variables.
But nesting styling would improve DX.

**Comment by zvonimirr** [comment]
That's completely fine!
I'm pretty sure we can leverage PostCSS for nesting anyway

**Comment by zvonimirr** [comment]
https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting
