### ISSUE TITLE
Add more useful info in HeadMeta

### ISSUE THREAD

**Issue by strdr4605** [cofeed-19/cofeed-19.github.io#5]
https://www.matuzo.at/blog/html-boilerplate/

No strong requirements, just need to pick features from the post above and see how it can feat cofeed-19. Further discussion in the PRs.

**Comment by cyborglaksh** [comment]
Hi, for the features I am a bit unclear.
Can you pls describe what's the issue we want to rectify?

**Comment by strdr4605** [comment]
I want to add useful tags in the index page of cofeed-19. 
If you are interested, just read the article in the description and see what HTML tags that are not in cofeed already can be added.
